Repository augenblick/CardShop, pull requests merged in 2024-03, with the labels that each got.

#14 10 json files describing products for each set
  CardShop/Repositories/Data/CardSets/cor.json
  CardShop/Repositories/Data/CardSets/ds2.json
  CardShop/Repositories/Data/CardSets/tat.json
  CardShop/Repositories/Data/CardSets/tp.json
  utils/rarity_tester/Cargo.lock
  utils/rarity_tester/Cargo.toml
  utils/rarity_tester/src/cards/pr.rs
  utils/rarity_tester/src/main.rs
Labels: enhancement

#15 #13 - Store Purchasing
  CardShop/CardShop.csproj
  CardShop/Controllers/CardShop.cs
  CardShop/Controllers/TestingController.cs
  CardShop/Interfaces/ICardProductBuilder.cs
  CardShop/Interfaces/IInventoryManager.cs
  CardShop/Interfaces/IInventoryRepository.cs
  CardShop/Interfaces/IShopManager.cs
  CardShop/Interfaces/IUserManager.cs
  CardShop/Interfaces/IUserRepository.cs
  CardShop/Logic/CardProductBuilder.cs
  CardShop/Logic/InventoryManager.cs
  CardShop/Logic/ShopManager.cs
  CardShop/Logic/UserManager.cs
  CardShop/Models/InventoryItem.cs
  CardShop/Models/Product.cs
  CardShop/Models/Request/PurchaseProductRequest.cs
  CardShop/Models/Response/PurchaseProductResponse.cs
  CardShop/Program.cs
  CardShop/Repositories/Data/CardShop
  CardShop/Repositories/InventoryRepository.cs
  CardShop/Repositories/Models/User.cs
  CardShop/Repositories/UserRepository.cs
Labels: enhancement

#22 Moved 4 JSON files to an alternate directory to prevent initialization errors
  CardShop/Repositories/Data/CardSets/invalid_rarity/cor.json
  CardShop/Repositories/Data/CardSets/invalid_rarity/ds2.json
  CardShop/Repositories/Data/CardSets/invalid_rarity/tat.json
  CardShop/Repositories/Data/CardSets/invalid_rarity/tp.json
Labels: bug

#24 #18 - add "open product(s)" support
  CardShop/CardShop.csproj
  CardShop/ConfigurationClasses/EnumSchemaFilter.cs
  CardShop/Controllers/CardShop.cs
  CardShop/Interfaces/ICardProductBuilder.cs
  CardShop/Interfaces/IInventoryManager.cs
  CardShop/Interfaces/IInventoryRepository.cs
  CardShop/Interfaces/IShopManager.cs
  CardShop/Logic/CardProductBuilder.cs
  CardShop/Logic/InventoryManager.cs
  CardShop/Logic/ShopManager.cs
  CardShop/Models/BoosterBox.cs
  CardShop/Models/BoosterPack.cs
  CardShop/Models/Card.cs
  CardShop/Models/CardSet.cs
  CardShop/Models/Product.cs
  CardShop/Models/Request/OpenInventoryProductsRequest.cs
  CardShop/Models/Request/PurchaseProductRequest.cs
  CardShop/Models/Response/OpenInventoryProductsResponse.cs
  CardShop/Program.cs
  CardShop/Repositories/Data/CardSets/anh.json
  CardShop/Repositories/Data/CardSets/cc.json
  CardShop/Repositories/Data/CardSets/dah.json
  CardShop/Repositories/Data/CardSets/edr.json
  CardShop/Repositories/Data/CardSets/hoth.json
  CardShop/Repositories/Data/CardSets/invalid_rarity/cor.json
  CardShop/Repositories/Data/CardSets/invalid_rarity/ds2.json
  CardShop/Repositories/Data/CardSets/invalid_rarity/tat.json
  CardShop/Repositories/Data/CardSets/invalid_rarity/tp.json
  CardShop/Repositories/Data/CardSets/jp.json
  CardShop/Repositories/Data/CardSets/pr.json
  CardShop/Repositories/Data/CardSets/se.json
  CardShop/Repositories/Data/CardShop
  CardShop/Repositories/InventoryRepository.cs
Labels: enhancement

#26 #20 - add support for arbitrary overall rarity codes that may be mapped to within a set
  CardShop/Controllers/TestingController.cs
  CardShop/Enums/RarityCode.cs
  CardShop/Interfaces/ICardProductBuilder.cs
  CardShop/Logic/CardProductBuilder.cs
  CardShop/Models/CardPool.cs
  CardShop/Models/CardSet.cs
  CardShop/Program.cs
  CardShop/Repositories/Data/CardSets/cor.json
  CardShop/Repositories/Data/CardSets/ds2.json
  CardShop/Repositories/Data/CardSets/tat.json
  CardShop/Repositories/Data/CardSets/tp.json
Labels: bug

#27 #25 - include all available card info in GetAllAvailableProductInfo response (optional via bool)
  CardShop/Controllers/CardShop.cs
  CardShop/Interfaces/ICardProductBuilder.cs
  CardShop/Logic/CardProductBuilder.cs
  CardShop/Models/Response/GetAllAvailableProductInfoResponse.cs
Labels: enhancement

#28 Create README.md
  README.md
Labels: documentation

#29 #19 - add support for Premiere Two-Player Intro Game
  CardShop/Logic/CardProductBuilder.cs
  CardShop/Logic/ShopManager.cs
  CardShop/Models/Product.cs
  CardShop/Repositories/Data/CardSets/2pp.json
  CardShop/Repositories/Data/CardSets/aside/2pp.json
Labels: enhancement

#32 Nathan/fix inventory insert bug
  CardShop/Controllers/CardShop.cs
  CardShop/Controllers/TestingController.cs
  CardShop/Extensions/InventoryExensions.cs
  CardShop/Logic/InventoryManager.cs
  CardShop/Logic/ShopManager.cs
  CardShop/Models/Product.cs
  CardShop/Models/Response/OpenMultipleProductTestResponse.cs
  CardShop/Repositories/Data/CardSets/2pp.json
  CardShop/Repositories/InventoryRepository.cs
Labels: bug

#34 Add GetAllAvailableCardSetInfo endpoint
  CardShop/Controllers/CardShop.cs
  CardShop/Interfaces/ICardProductBuilder.cs
  CardShop/Logic/CardProductBuilder.cs
  CardShop/Models/CardSetInfo.cs
  CardShop/Models/Response/GetAllAvailableCardSetInfoResponse.cs
Labels: enhancement

#36 #34 - fix bug causing incorrect inventory inserts when opening products
  CardShop/Controllers/TestingController.cs
  CardShop/Logic/InventoryManager.cs
  CardShop/Repositories/InventoryRepository.cs
Labels: bug

#38 Add DB on startup
  .gitignore
  CardShop/CardShop.csproj
  CardShop/CardTestDb
  CardShop/DesignNotes.md
  CardShop/Interfaces/IUserManager.cs
  CardShop/Interfaces/IUserRepository.cs
  CardShop/Logic/DbBuilder.cs
  CardShop/Logic/ShopManager.cs
  CardShop/Logic/UserManager.cs
  CardShop/Program.cs
  CardShop/Properties/launchSettings.json
  CardShop/Repositories/CardTestDb
  CardShop/Repositories/Data/CardShop
  CardShop/Repositories/Models/User.cs
  CardShop/Repositories/UserRepository.cs
Labels: enhancement
